version: '3.4'
services:
  goitcshw06:
    image: goitcshw06
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    depends_on:
      - mongo
      - socket

  socket:
    http_server:
    context: .
    dockerfile: ./Dockerfile.socket
    build: ./http_server
    ports:
      - "8000:8000"
    depends_on:
      - socket_server
  socket_server:
    build: ./socket_server
    ports:
      - "5000:5000"

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data: